name: Deploy C# Web App to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Điều chỉnh phiên bản .NET của bạn
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build project
        run: dotnet build --configuration Release --no-restore
      
      - name: Publish project
        run: dotnet publish --configuration Release --output ./publish
      
      # Nếu sử dụng Blazor WebAssembly
      - name: Change base-tag in index.html for GitHub Pages
        if: success() && exists('./publish/wwwroot/index.html')
        run: |
          sed -i 's/<base href="\/" \/>/<base href="\/WebRTC\/" \/>/g' ./publish/wwwroot/index.html
          cp ./publish/wwwroot/index.html ./publish/wwwroot/404.html
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './publish/wwwroot'  # Đối với Blazor WebAssembly
          # path: './publish'  # Đối với các ứng dụng web khác
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2