name: Build and Push to Deploy Branch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

  # Thêm permissions để cho phép GitHub Actions ghi vào repository
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build project
        run: dotnet build --configuration Release --no-restore
      
      - name: Publish project
        run: dotnet publish --configuration Release --output ./publish
      
      - name: Debug GitHub Token and Repo
        run: |
          echo "GITHUB_TOKEN is set: ${GITHUB_TOKEN:-not set}"
          git remote -v
          echo "Deploying to branch: deploy"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Deploy to deploy branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./publish
          branch: deploy
          clean: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}